### ISSUE TITLE
release new version 

### ISSUE THREAD

**Issue by pocke** [pocke/exception_notification-bugsnag#7]
Wait releasing this patch https://github.com/smartinez87/exception_notification/pull/411

**Comment by ybiquitous** [comment]
The new version 4.3.0 is published! 🎉 🎉 🎉 

- https://github.com/smartinez87/exception_notification/releases/tag/v4.3.0
- https://github.com/smartinez87/exception_notification/blob/v4.3.0/CHANGELOG.rdoc

**Comment by pocke** [comment]
I'll release the new version after merge #9 .

**Comment by ybiquitous** [comment]
I opened PR #11, instead of #9.

**Comment by pocke** [comment]
I released v0.3.0.

**Comment by ybiquitous** [comment]
Thanks a lot! 🎉

**Comment by ybiquitous** [comment]
@pocke Are you working on CHANGELOG? Otherwise, I'm ready to do it.

**Comment by pocke** [comment]
I completely forgot CHANGELOG. Could you please update it?

**Comment by ybiquitous** [comment]
OK! 👌
